version: '2'
services:
    abcideaapp-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/AbcideaApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=AbcideaApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
